### ISSUE TITLE
Format for adding user via vipw is incorrect

### ISSUE THREAD

**Issue by DCHuber** [rricharz/pidp11-2.11bsd#1]
The example entry on the AddUser document leads vipw to respond with "corrupted entry"   when you try to save the document.
_firstname::201:20:fullname:/home/firstname:/bin/tcsh_

It needs to address the inclusion of password change and account expiration fields now required by passwd.  This  string works with vipw:  

_firstname::201:20::::fullname:/home/firstname:/bin/tcsh_

**Comment by rricharz** [comment]
Fixed. Thanks for the information.
